# Use an official Node runtime as a parent image
FROM node:20

# Set the working directory to /app/client
WORKDIR /app/client

# Copy package.json and package-lock.json to the working directory
COPY ./client/package*.json ./

# Install app dependencies
RUN npm install

# Copy the current directory contents into the container at /app/client
COPY ./client .

# Expose the port used by Vite during development
EXPOSE 8080

# Run Vite development server
CMD ["npm", "run", "dev", "--", "--host"]